import banner from './banner.jpeg';
import banner2 from './banner2.jpeg';
import banner12 from './banner12.jpeg';
import banner5 from './banner5.jpeg';
import about from './about.jpeg';
import about2 from './about2.jpeg';
import salon from './salon.jpeg';
import Style from './31.jpeg';
import haircut from './haircut.jpeg';
import womenhairstyle from './womenhairstyle.jpeg';
import reser1 from './1.jpeg';
import reser2 from './5.jpeg';
import reser3 from './31.jpeg';
import chef1 from './chef1.jpeg';
import chef2 from './chef2.jpeg';
import chef3 from './chef3.jpeg';
import kristane from './kristane.png';
import Aboutcomponent from './7.jpeg'
import banner8 from  './banner8.jpeg'
import gallery2 from './6.jpg.jpeg'
import gallery3 from './9.jpg.jpeg'
import gallery4 from './kristane.jpeg'
import gallery5 from './stylish.jpg.jpeg'
import gallery6 from './5.jpg.jpeg'
import gallery7 from './1.jpg.jpeg'
import gallery8 from './4.jpg.jpeg'
import hairsalon from "./hairsalon.jpeg"
import hairsalonmen from "./hairsalonmen.jpeg"
import hairsalonwomen from "./hairsalonwomen.jpeg"
import before from "./before.jpeg"
import after from "./after.jpeg"
import  KeratinnTreatment from "./KeratinTreatment.jpeg"
import waxing from "./waxing.jpeg" 
import menwax from "./waxing-for-men.jpeg"
import womenwax from "./body-waxing-service.jpeg"
import haircolor from "./haircolor.jpeg"
import haircolor2 from "./8819.jpeg"
import coloring from "./coloring.jpeg"
import nanoplastia from "./4415.jpeg"
import nanoplastiabefore from "./Nanoplastia-before.jpeg"
import nanoplastiaafter from "./Nanoplastia-after.jpeg"
import facial from "./16770.jpeg"
import facialservices from "./facial.jpeg"
import facialservicess from "./facialservice.jpeg"


export {banner,nanoplastia,facialservices,facialservicess,facial,nanoplastiabefore,nanoplastiaafter, banner2,coloring ,KeratinnTreatment,haircolor2,after,haircolor,womenwax,waxing,menwax, banner12,hairsalonmen,hairsalonwomen,before, banner5 ,gallery2,gallery5,gallery6,gallery7,gallery8, about, about2 ,salon ,gallery4 , Style ,hairsalon,gallery3, haircut , womenhairstyle , reser1 , reser2 ,banner8, reser3 ,chef1 , chef2 , chef3,kristane,Aboutcomponent};